# Generated by Django 4.2 on 2023-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m6_todo_app', '0002_alter_tasks_end_alter_tasks_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
